### PR TITLE
Configure indexes

### PR DESCRIPTION
**Pull request by tdesvenain**

### CODE REVIEW

**Comment by tdesvenain** [comment]
I'd like to test it on travis, how could i, now ?

**Comment by vangheem** [comment]
hmmm, I guess there isn't a manual way to do is that I can see. I've turned travis back on for it. I'd be very grateful if you fixed it. Thank you.

**Comment by tdesvenain** [comment]
@vangheem it works :) please let me rebase it

**Comment by tdesvenain** [comment]
@vangheem done, could you merge this now please ?

**Comment by vangheem** [comment]
Thanks so much!

**Pull request merged**
