### PR TITLE
Es shards

### PR DESCRIPTION
**Pull request by zopyx**
Configuration support for ES replicas and shards

### CODE REVIEW

**Comment by vangheem** [comment]
Thanks! FYI, tests fail on travis because of elasticsearch versions; however, they should succeed locally.

**Comment by tdesvenain** [comment]
Hi @zopyx, the tests work on travis now, you could rebase and it should be ok.
If you prefer so, i'm available to do this.

**Comment by tdesvenain** [comment]
I must say i'm very interested in your pr :)

**Comment by tdesvenain** [comment]
cf #22

**Pull request closed without merging**
