### PR TITLE
Issue #63 Now ensuring we unicode string value would work for both py…

### PR DESCRIPTION
**Pull request by nazrulworld**

### CODE REVIEW

**Comment by nazrulworld** [comment]
@lucid-0 Can you please have a look at this PR?

**Comment by nazrulworld** [comment]
> Should we add six to install_requires or something, looks like we're introducing it as dependency. But looks good to me.

I think Plone/Zope itself has six dependencies, so it's OK in my opinion that not add in our install requires
@lucid-0 if possible, please make a release on PyPI.

**Comment by lucid-0** [comment]
Tried to make a release just now, I don't have access to the project on PyPI.  I see a colleague of mine is a maintainer I will ask to be added in the morning.

**Comment by lucid-0** [comment]
Okay, 3.0.4 is on pypi

**Pull request merged**
