### PR TITLE
Prevent UnicodeDecodeError in sending the data to ES

### PR DESCRIPTION
**Pull request by jaroel**

### CODE REVIEW

**Comment by vangheem** [comment]
fyi, this package may change quite a bit soon. I'm going to move it to only overriding full text indexes and only querying elasticsearch if the query is searching on the full text field.

**Comment by jaroel** [comment]
So, like collective.elasticindex ?

**Comment by vangheem** [comment]
No, it's still going to index security so it should be safe to use with
private content as well.

**Comment by lukasgraf** [comment]
@vangheem does this mean you'll drop the functionality for `collective.elasticsearch` to replace the entire Catalog?

**Comment by vangheem** [comment]
@lukasgraf Yes, it will no longer be a replacement of the portal catalog. The reason being that the performance improvements were only there with very large websites and when using searchable text index.

Replacing the entire catalog meant that you're doing multiple search requests back to elastic for every page load(because a basic page load includes many queries) and it was actually faster to use the built in catalog(unless you had a huge website). The real benefit is searchable text.

This is will turn into a more subtle catalog replacement where only queries that are using searchable text index will use go to elastic. Also, indexing searchable text can then be done as a on transaction commit hook and the package no longer needs to do that complicated and messy object tracking to deal with transactions.

This is a hard problem and the fact that no search engines are transaction aware makes it annoying. I've never made a final release of this package simply because I never felt good enough about how the implementation was done.

**Comment by lukasgraf** [comment]
@vangheem thank you for your detailed response.

Yeah, I wondered how you dealt with the fact that ES isn't transaction aware. I noticed you implemented a [DataManager](https://github.com/collective/collective.elasticsearch/blob/648247de5199f61f4e045dbf2295b292daafc0d8/collective/elasticsearch/datamanager.py#L123-L124), but wasn't sure whether that would guarantee any sort of transactionality or not.

Thanks for giving us a heads up though about we're you're thinking of taking `c.elasticsearch`. I'm currently evaluating it for use in a rather large deployment (> 2.5 TB including blobs). And one of the issues we're facing there is not just the need for better search, but also how conflict-prone the catalog is (particularly with concurrent content creation), how expensive index updates are, and how badly it performs at scale. So the fact `c.elasticsearch` offers a drop-in replacement seemed promising, but I haven't gotten around to testing it in practice in any detail.

I've also been meaning to ask you what your plans are for `c.elasticsearch` in general, but I'll create a separate issue for that (in short, whether you'd be ok with pull requests that implement features found in [`collective.solr`](https://github.com/collective/collective.solr), or you'd rather keep it simple).

**Comment by vangheem** [comment]
I've love to get more features!

Also, getting rid of the searchable text indexes will still be a pretty decent performance improvement and it should help out a decent amount with concurrent write issues.

I was also planning on integrating async for the indexing part so it's not delaying at all.

**Pull request merged**
